### ISSUE TITLE
[enhancement] - update twrnc to latest version

### ISSUE THREAD

**Issue by rimsila** [finkef/react-native-tailwind.macro#10]
I have seen [twrnc](https://github.com/jaredh159/tailwind-react-native-classnames) was release  v3.2.0. Do you have plan to upgrade it? thanks you

**Comment by finkef** [comment]
Yes, absolutely! From a quick first look, it seems that we can just upgrade and it _could_ work right out of the box.

PRs always welcome of course! 🙌

**Comment by finkef** [comment]
Closed by #14.
