### ISSUE TITLE
example next error Cannot find module 'react-native-tailwind.macro'

### ISSUE THREAD

**Issue by oste** [finkef/react-native-tailwind.macro#3]
When attempting to run the next example I am getting this error. I am running yarn v1

Cannot find module 'react-native-tailwind.macro' from '/Users/mike/react-native-tailwind.macro/examples/next/pages'

**Comment by finkef** [comment]
Check out https://github.com/finkef/react-native-tailwind.macro/blob/main/CONTRIBUTING.md for instructions on working with the examples and let me know if that fixes the problem. 🙂
