### ISSUE TITLE
Prop `style` did not match. Server: 

### ISSUE THREAD

**Issue by oste** [finkef/react-native-tailwind.macro#4]
I managed to get the next.js example app running but noticed in the chrome console `Prop style did not match. Server: `

From my experience, the way around this is to pass the styles as initial props in `getStaticProps/getInitialProps`. This is what I have been doing until now. It comes with its drawbacks so maybe it won't work here 🤔

**Comment by finkef** [comment]
Saw this as well, didn't notice any issues this would cause in the app. Do you have any idea where this issue might originate?

**Comment by oste** [comment]
It will cause a re-render on load. It happens when the styles that are generated by the server don't match what is rendered on the client. Which causes the re-render
