### ISSUE TITLE
Tailwind intellisense support in prefix

### ISSUE THREAD

**Issue by rimsila** [finkef/react-native-tailwind.macro#6]
everyone who have any classRegex to make Tailwind intellisense work in prefix ex: ios:(text-blue-500)
I have try  `"tw=[\"'`]([^\"'`]*)",` but it work only outside prefix. 

<img width="840" alt="Screen Shot 2021-12-16 at 12 29 10 AM" src="https://user-images.githubusercontent.com/51617383/146235679-a3a92cb0-0d8e-4e85-afa7-ed7161041764.png">

But it work if the class have **space** around ( )
` ios:( text-blue-500 )`

<img width="840" alt="Screen Shot 2021-12-16 at 12 34 42 AM" src="https://user-images.githubusercontent.com/51617383/146236476-688d7079-0d42-4577-b7d3-ca9731a6411e.png">

**Comment by oste** [comment]
@rimsila have you seen this thread? https://github.com/jaredh159/tailwind-react-native-classnames/issues/78
I haven't tried it yet myself but hopefully some of those ideas can help.

**Comment by finkef** [comment]
Personally, I'm using the [twin plugin](https://marketplace.visualstudio.com/items?itemName=lightyen.tailwindcss-intellisense-twin) and it's working great so far.

**Comment by oste** [comment]
@finkef were you able to just install the plugin and have it work? For me it seems to be doing some syntax highlighting but I am not getting any auto complete

**Comment by oste** [comment]
I was able to get this working using [tailwind intellisense plugin](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) after adding tw as a class attribute

<img width="801" alt="Screen Shot 2021-12-22 at 9 39 30 PM" src="https://user-images.githubusercontent.com/350275/147179816-bcfb8852-5016-46c4-bccf-7eb6f484f3ae.png">
