### ISSUE TITLE
Dark mode not working using useTailwindStyles in web

### ISSUE THREAD

**Issue by rimsila** [finkef/react-native-tailwind.macro#7]
Dark mode not working in useTailwindStyles in web only working in mobile
https://github.com/finkef/react-native-tailwind.macro/blob/main/examples/expo/src/Button.tsx

![Screen Shot 2021-12-16 at 1 52 34 AM](https://user-images.githubusercontent.com/51617383/146248032-b6b08430-1ae6-4d55-91bf-258d0ea5c05f.png)

**Comment by finkef** [comment]
Good catch, it was missing setting the `dataSet` prop which is the main caveat of `useTailwindStyles` and easy to forget. Fixed in #8.
